# Generated by Django 6.0.4 on 2026-08-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description_markdown', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=16)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=8)),
                ('effort', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=8)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI brain dump')], default='manual', max_length=8)),
                ('original_transcript_snippet', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status', 'position', 'created_at'],
            },
        ),
    ]
