# Generated by Django 6.0.4 on 2026-08-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_require_kanbantask_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbantask',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
