# Generated by Django 6.0.4 on 2026-08-25 11:33

import cv.schema
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('sections', models.JSONField(blank=True, default=cv.schema.empty_sections)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
