# Generated by Django 6.0.4 on 2026-08-27 01:14

import cv.schema
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_fix_cvprofile_id_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvStylePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_choice', models.CharField(default='system-serif', max_length=40)),
                ('theme_choice', models.CharField(default='classic-dark', max_length=40)),
                ('template_choice', models.CharField(default='two-column', max_length=40)),
                ('section_order', models.JSONField(default=cv.schema.default_section_order)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
