# Generated by Django 6.0.4 on 2026-08-27 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_cvstylepreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, default='', max_length=200)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('job_description', models.TextField()),
                ('generated_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='cv.cvprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
