# Generated by Django 6.0.4 on 2026-08-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassroomCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField(blank=True, default="")),
                ("refresh_token", models.TextField(blank=True, default="")),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("scope", models.CharField(blank=True, default="", max_length=1000)),
                (
                    "google_sub",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("email", models.CharField(blank=True, default="", max_length=255)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "picture_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClassroomSubmissionDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(max_length=64)),
                (
                    "course_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("coursework_id", models.CharField(max_length=64)),
                (
                    "coursework_title",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("ASSIGNMENT", "Assignment"),
                            ("SHORT_ANSWER_QUESTION", "Short answer question"),
                        ],
                        max_length=32,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "google_submission_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("answer_text", models.TextField(blank=True, default="")),
                (
                    "solution_doc_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "solution_doc_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("turned_in", "Turned in")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("google_turned_in_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
