# Generated by Django 6.0.4 on 2026-08-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomsubmissiondraft',
            name='attachment_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='classroomsubmissiondraft',
            name='coursework_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='classroomsubmissiondraft',
            name='extra_instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
