# Generated by Django 6.0.4 on 2026-08-28 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_providercredential_modelpreference_max_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('awaiting_confirmation', 'Awaiting confirmation'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=24)),
                ('pending_action', models.JSONField(blank=True, null=True)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('result_text', models.TextField(blank=True, default='')),
                ('result_mood', models.CharField(blank=True, default='', max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tasks', to='core.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
