# Generated by Django 6.0.4 on 2026-08-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='current_step',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
