// Service Worker — registered automatically by vite-plugin-pwa (Workbox)
// This file is intentionally minimal; Workbox injects its own runtime here
// during the build step. The comment below is the Workbox injection point.

// Precache all assets generated by Vite build
import { precacheAndRoute, cleanupOutdatedCaches } from "workbox-precaching";
import { clientsClaim } from "workbox-core";
import { registerRoute } from "workbox-routing";
import {
  NetworkFirst,
  StaleWhileRevalidate,
  CacheFirst,
} from "workbox-strategies";
import { ExpirationPlugin } from "workbox-expiration";

// Immediately claim any new clients (tabs) so updates take effect quickly
self.skipWaiting();
clientsClaim();

// Workbox injects the precache manifest here at build time
precacheAndRoute(self.__WB_MANIFEST || []);

// Remove outdated caches from previous SW versions
cleanupOutdatedCaches();

// ── API calls: Network-first, fall back to cache for 1 minute ──────────
registerRoute(
  ({ url }) => url.pathname.startsWith("/api/"),
  new NetworkFirst({
    cacheName: "mirabel-api-cache",
    networkTimeoutSeconds: 5,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60, // 1 minute
      }),
    ],
  })
);

// ── Google Fonts: cache-first, keep for 1 year ──────────────────────────
registerRoute(
  ({ url }) =>
    url.origin === "https://fonts.googleapis.com" ||
    url.origin === "https://fonts.gstatic.com",
  new CacheFirst({
    cacheName: "mirabel-fonts-cache",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60,
      }),
    ],
  })
);

// ── Static assets (JS, CSS, images): stale-while-revalidate ────────────
registerRoute(
  ({ request }) =>
    request.destination === "script" ||
    request.destination === "style" ||
    request.destination === "image",
  new StaleWhileRevalidate({
    cacheName: "mirabel-static-cache",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 1 week
      }),
    ],
  })
);
