# Generated by Django 6.0.4 on 2026-09-08 04:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadsAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('profile_sync', 'Profile Sync'), ('token_refresh', 'Token Refresh'), ('rate_limit_sync', 'Rate Limit Sync'), ('daily_briefing', 'Daily Threads Briefing'), ('weekly_report', 'Weekly Threads Report')], max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('interval_hours', models.PositiveIntegerField(default=6)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=16)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadsCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('permission_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_private_profile', models.BooleanField(default=False)),
                ('needs_reauth', models.BooleanField(default=False)),
                ('scope', models.CharField(blank=True, default='', max_length=500)),
                ('threads_user_id', models.CharField(blank=True, default='', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('biography', models.TextField(blank=True, default='')),
                ('profile_picture_url', models.URLField(blank=True, default='', max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadsDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='')),
                ('reply_control', models.CharField(choices=[('everyone', 'Everyone'), ('accounts_you_follow', 'Profiles you follow'), ('mentioned_only', 'Profiles you mention')], default='everyone', max_length=30)),
                ('link_url', models.URLField(blank=True, default='', max_length=1000)),
                ('image', models.FileField(blank=True, null=True, upload_to='threads/')),
                ('prompt', models.TextField(blank=True, default='')),
                ('tone', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('container_id', models.CharField(blank=True, default='', max_length=64)),
                ('container_status', models.CharField(blank=True, default='', max_length=32)),
                ('container_expires_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('parent_thread_id', models.CharField(blank=True, default='', max_length=64)),
                ('threads_post_id', models.CharField(blank=True, default='', max_length=255)),
                ('permalink', models.URLField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadsProfileSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('biography', models.TextField(blank=True, default='')),
                ('profile_picture_url', models.URLField(blank=True, default='', max_length=1000)),
                ('is_private_profile', models.BooleanField(default=False)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadsRateLimitSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('quota_usage', models.IntegerField(default=0)),
                ('quota_total', models.IntegerField(default=250)),
                ('reply_quota_usage', models.IntegerField(blank=True, null=True)),
                ('reply_quota_total', models.IntegerField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadsAutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='threads.threadsautomation')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadsProfileChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=32)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='threads.threadsprofilesnapshot')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
