# Generated by Django 6.0.4 on 2026-09-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartesiaTTSKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('api_key', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('untested', 'Untested'), ('ok', 'OK'), ('quota_exceeded', 'Quota exceeded'), ('error', 'Error')], default='untested', max_length=20)),
                ('status_note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
