# Generated by Django 6.0.4 on 2026-08-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, default='', max_length=255)),
                ('member_sub', models.CharField(blank=True, default='', max_length=255)),
                ('member_urn', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('picture_url', models.URLField(blank=True, default='', max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedInDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('CONNECTIONS', 'Connections')], default='PUBLIC', max_length=20)),
                ('link_url', models.URLField(blank=True, default='', max_length=1000)),
                ('image', models.FileField(blank=True, null=True, upload_to='linkedin/')),
                ('prompt', models.TextField(blank=True, default='')),
                ('tone', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('linkedin_post_urn', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
