# Generated by Django 6.0.4 on 2026-09-12 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('prompt', models.TextField()),
                ('revised_prompt', models.TextField(blank=True, default='')),
                ('negative_prompt', models.TextField(blank=True, default='')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('provider', models.CharField(default='google', max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media_assets/%Y/%m/')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='media_assets/thumbnails/%Y/%m/')),
                ('aspect_ratio', models.CharField(blank=True, default='1:1', max_length=20)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('generation_parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_assets', to='media_assets.mediaasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='google', max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='video', max_length=20)),
                ('prompt', models.TextField()),
                ('aspect_ratio', models.CharField(default='16:9', max_length=20)),
                ('duration_seconds', models.IntegerField(default=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('operation_name', models.CharField(blank=True, default='', max_length=255)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('progress_percent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='media_assets.mediaasset')),
                ('source_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_jobs', to='media_assets.mediaasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
