# Generated by Django 6.0.4 on 2026-05-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_label', models.CharField(db_index=True, max_length=64)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('summary_text', models.TextField()),
                ('dominant_moods', models.JSONField(default=list)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('chroma_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['user_label', '-period_end'], name='memory_memo_user_la_9ed772_idx')],
            },
        ),
    ]
