# Generated by Django 6.0.4 on 2026-08-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='memorysummary',
            name='memory_memo_user_la_9ed772_idx',
        ),
        migrations.AddIndex(
            model_name='memorysummary',
            index=models.Index(fields=['-period_end'], name='memory_memo_period__031888_idx'),
        ),
        migrations.RemoveField(
            model_name='memorysummary',
            name='user_label',
        ),
    ]
