# Generated by Django 6.0.4 on 2026-08-30 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_providercredential_modelpreference_max_tokens_and_more'),
        ('memory', '0002_remove_memorysummary_memory_memo_user_la_9ed772_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_text', models.TextField()),
                ('fact_type', models.CharField(choices=[('preference', 'Preference'), ('biographical', 'Biographical'), ('relationship', 'Relationship'), ('goal', 'Goal'), ('constraint', 'Constraint'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded')], default='active', max_length=20)),
                ('chroma_id', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_facts', to='core.message')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_set', to='memory.memoryfact')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'fact_type'], name='memory_memo_status_b414e1_idx')],
            },
        ),
    ]
