# Generated by Django 6.0.4 on 2026-09-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0002_scheduledemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
    ]
