# Generated by Django 6.0.4 on 2026-08-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user_label',
        ),
    ]
