# Generated by Django 6.0.4 on 2026-08-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_conversation_user_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='anthropic', max_length=20)),
                ('model', models.CharField(default='claude-sonnet-5', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
