# Generated by Django 6.0.4 on 2026-08-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_modelpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20, unique=True)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='modelpreference',
            name='max_tokens',
            field=models.PositiveIntegerField(default=400),
        ),
        migrations.AddField(
            model_name='modelpreference',
            name='temperature',
            field=models.FloatField(default=1.0),
        ),
    ]
