# Generated by Django 6.0.4 on 2026-08-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_providercredential_modelpreference_max_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_budget_usd', models.FloatField(blank=True, null=True)),
                ('alert_thresholds', models.CharField(default='50,75,90,100', max_length=100)),
                ('alerts_fired', models.CharField(blank=True, default='', max_length=100)),
                ('alerts_period', models.CharField(blank=True, default='', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=20)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('call_site', models.CharField(db_index=True, max_length=50)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cache_read_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cache_write_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('estimated', models.BooleanField(default=False)),
                ('error', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='core_llmcal_created_3dfec3_idx'), models.Index(fields=['provider', 'created_at'], name='core_llmcal_provide_1f2a0e_idx'), models.Index(fields=['model', 'created_at'], name='core_llmcal_model_ab5686_idx'), models.Index(fields=['call_site', 'created_at'], name='core_llmcal_call_si_32f215_idx')],
            },
        ),
        migrations.CreateModel(
            name='OptimizationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('memory_gate', 'Memory gate'), ('memory_retrieval', 'Memory retrieval'), ('dedup', 'Memory dedup'), ('tool_routing', 'Agent tool routing'), ('agent_trim', 'Agent history trim'), ('truncation', 'Content truncation')], db_index=True, max_length=30)),
                ('outcome', models.CharField(blank=True, default='', max_length=30)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('extra', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'created_at'], name='core_optimi_categor_55a881_idx')],
            },
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('input_price_per_1m', models.FloatField(blank=True, null=True)),
                ('output_price_per_1m', models.FloatField(blank=True, null=True)),
                ('cache_read_price_per_1m', models.FloatField(blank=True, null=True)),
                ('cache_write_price_per_1m', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'model'), name='unique_pricing_provider_model')],
            },
        ),
    ]
