# Generated by Django 6.0.4 on 2026-09-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_budgetsettings_llmcalllog_optimizationevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpreference',
            name='fast_conversation_mode',
            field=models.BooleanField(default=False),
        ),
    ]
