# Generated by Django 6.0.4 on 2026-09-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_modelpreference_fast_conversation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providercredential',
            name='api_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
